version: "4.31.1"

services:
  database:
    container_name: cursodjango_database
    image: postgres:16.3
    restart: always
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
      - .env:/.env
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=pythonpro
      - POSTGRES_USER=pythonpro
      - POSTGRES_DB=cursodjango
    ports:
      - 5434:5432